name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Run Tests
    - name: Run Tests
      run: |
        composer install --no-dev
        php artisan test

    # Step 4: Deploy with Deployer
    - name: Install Deployer
      run: |
        curl -LO https://deployer.org/deployer.phar
        chmod +x deployer.phar
        mv deployer.phar /usr/local/bin/dep

    - name: Deploy Application
      run: dep deploy

      # Deploy using Deployer
      - name: Deploy Laravel App
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 104.156.254.130 >> ~/.ssh/known_hosts
          dep deploy
